sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t richeek45/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true richeek45/react-test npm test 

after_success:
  - docker build -t richeek45/multi-client ./client
  - docker build -t richeek45/multi-nginx ./nginx
  - docker build -t richeek45/multi-server ./server
  - docker build -t richeek45/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push richeek45/multi-client
  - docker push richeek45/multi-nginx
  - docker push richeek45/multi-server
  - docker push richeek45/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-701670403746
  bucket_path: docker-multi
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY